version: '3.9'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    restart: always

  api:
    build:
      context: .
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
    restart: always
    depends_on:
      - mongodb
    volumes:
      - ./application:/app/application