
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    restart: always

  api:
    build:
      context: .
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - MONGODB_DB=users
      - MONGODB_HOST=mongodb
      - MONGODB_USER=admin
      - MONGODB_PASSWORD=admin
    restart: always
    depends_on:
      - mongodb
    volumes:
      - ./application:/app/application